
#database configuration

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/exam
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

